### ISSUE TITLE
USER STORY: Clear interface

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#1]
### EPIC: Navigating through the website

***

### USER STORY
As a ***shopper***, I want to ***be greeted with a clearly structured interface***, so that I can ***navigate through the website with ease***

***

### ACCEPTANCE CRITERIA
- [ ] Visually appealing home page
- [ ] Navbar to make the site easy to navigate
- [ ] Logo in top left corner of each page which functions as a home button
***

### TASKS
- [ ] Create home page
- [ ] Create logo
- [ ] Create navbar
- [ ] Ensure same design is featured on each page
- [ ] Test functionality
