### ISSUE TITLE
USER STORY: Viewing searches

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#11]
### EPIC: Sorting and searching for products

***

### USER STORY
As a ***shopper***, I want to ***view what I have searched for and the number of items I have searched for***, so that I can ***see whether the product I want is available***

***

### ACCEPTANCE CRITERIA
- [ ] User is able to see a list of their search for items
- [ ] Total number of products displayed at the top of the screen

***

### TASKS
- [ ] Add view and template for seeing searched for products
- [ ] Add functionality to show number of products
- [ ] Customise styling
- [ ] Test functionality
