### ISSUE TITLE
USER STORY: Add item to bag and choose quantity

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#12]
### EPIC: Purchasing and checkout

***

### USER STORY
As a ***shopper***, I want to ***be able to add an item to my basket and choose how many of an item I want to buy***, so that I can ***select the quantity I desire in case I want more than one of the item***

***

### ACCEPTANCE CRITERIA
- [ ] User to be able to add an item to their bag
- [ ] User to be able to choose the quantity of their chosen item
- [ ] User should not be able to choose a quantity lower than 1
***

### TASKS
- [ ] Create functionality to add item to bag
- [ ] Create increase and decrease buttons for the item quantity on the product detail page
- [ ] Customise styling
- [ ] Test functionality
