### ISSUE TITLE
USER STORY: Edit bag

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#14]
### EPIC: Purchasing and checkout

***

### USER STORY
As a ***shopper***, I want to ***adjust the quantity of an item from the checkout page***, so that I can ***easily edit my purchase before the checkout***
***

### ACCEPTANCE CRITERIA
- [ ] Checkout page to allow users to edit the quantity of their items
- [ ]  User should not be able to choose a quantity lower than 1

***

### TASKS
- [ ] Create increase and decrease buttons for the item quantity on the checkout page
- [ ] Customise styling
- [ ] Test functionality
