### ISSUE TITLE
USER STORY: View delivery costs

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#18]
### EPIC: Purchasing and checkout

***

### USER STORY
As a ***shopper***, I want to ***view any delivery costs on the checkout page***, so that I can ***see how much I am paying for delivery and if I'd rather purchase something extra to avoid this cost***

***

### ACCEPTANCE CRITERIA
- [ ] Checkout page shows the delivery cost along with the total cost
- [ ] Informs the user how much more they can spend to get free delivery

***

### TASKS
- [ ] Add functionality to show delivery costs and how much more the user could spend to get free delivery
