### ISSUE TITLE
USER STORY: Responsive site

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#2]
### EPIC: Navigating through the website

***

### USER STORY
As a ***shopper***, I want ***the website to be responsive***, so that I can ***access it on a range of devices***

***

### ACCEPTANCE CRITERIA
- [x] Website needs to be created with responsive design starting at 320 px for mobiles, tablets and desktops

***

### TASKS
- [x] Create media queries starting with mobile first
- [x] Create hamburger navbar for mobile and tablet devices
- [x] Customise styling
- [x] Test functionality
