### ISSUE TITLE
USER STORY: Inputting card details

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#21]
### EPIC: Purchasing and checkout

***

### USER STORY
As a ***shopper***, I want to ***be able to put in my card details***, so that I can ***make a purchase***

***

### ACCEPTANCE CRITERIA
- [ ] Users able to put in card details using Stripe
- [ ] Clear error messages to appear for any incorrect inputs

***

### TASKS
- [ ] Create functionality for making card payments by setting up Stripe
- [ ] Ensure there are appropriate error messages for any incorrect inputs
- [ ] Customise styling
- [ ] Test functionality
