### ISSUE TITLE
USER STORY: Sign up confirmation email

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#24]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***new user***, I want to ***receive an email confirmation after signing up***, so that I can ***confirm that my account is set up successfully***

***

### ACCEPTANCE CRITERIA
- [ ] User will receive an emailing confirming their account ahs been set up after signing up

***

### TASKS
- [ ] Add email functionality to sign up
- [ ] Create message to be emailed to new users
- [ ] Customise styling
- [ ] Test functionality
