### ISSUE TITLE
USER STORY: Sign up page

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#3]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***new user***, I want to ***navigate to the sign up page***, so that I can ***create an account***

***

### ACCEPTANCE CRITERIA
- [ ] User is able to create an account
- [ ] Validation errors will be presented to user for any invalid inputs
- [ ] UX is visually appealing

***

### TASKS
- [ ] Implement sign up form and functionality using allauth
- [ ] Customise styling
- [ ] Test functionality
