### ISSUE TITLE
USER STORY: Adding to a wishlist

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#30]
### EPIC: Adding items to a wishlist

***

### USER STORY
As a ***registered user***, I want to ***be able to add a product that I like to a wishlist***, so that I can ***save the item without having to add it to the checkout***

***

### ACCEPTANCE CRITERIA
- [ ] Signed in users can add products to their personal wishlist

***

### TASKS
- [ ] Create wishlist functionality to enable users to click a heart icon to add their favourites
- [ ] Should only be available to signed in users
- [ ] Test functionality
