### ISSUE TITLE
USER STORY: View favourited items

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#31]
### EPIC: Adding items to a wishlist

***

### USER STORY
As a ***registered user***, I want to ***be able to view my favourited items in my wishlist***, so that I can ***see all of the items that I like before I buy them***

***

### ACCEPTANCE CRITERIA
- [ ] Signed in users can view products in their personal wishlist

***

### TASKS
- [ ] Create wishlist page where users can see all of their favourites
- [ ] Should only be available to signed in users
- [ ] Test functionality
