### ISSUE TITLE
USER STORY: Submit FAQs

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#34]
### EPIC: Frequently asked questions

***

### USER STORY
As a ***registered user***, I want to ***be able to submit a question on the FAQ page***, so that I can ***enquire about any general concerns***

***

### ACCEPTANCE CRITERIA
- [ ] Form to be available at bottom of FAQs page for signed in users to submit their own questions
- [ ] Only accessible to signed in users

***

### TASKS
- [ ] Create FAQs form available to signed in users
- [ ] Customise styling
- [ ] Test functionality
