### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#4]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***registered user***, I want to ***login to my account***, so that I can ***make purchases***

***

### ACCEPTANCE CRITERIA
- [x] User is able to sign in to their account. 
- [x] UX is visually appealing

***

### TASKS
- [x] Implement login form and functionality using allauth
- [x] Customise styling
- [x] Test functionality
