### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#5]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***registered user***, I want to ***log out of my account***, so that I can ***protect my information from being accessed by others***

***

### ACCEPTANCE CRITERIA
- [x] User is able to sign out of their account
- [x] UX is visually appealing

***

### TASKS
- [x] Implement log out form and functionality using allauth
- [x] Customise styling
- [x] Test functionality
