### ISSUE TITLE
USER STORY: View products

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#6]
### EPIC: Navigating through the website

***

### USER STORY
As a ***shopper***, I want to ***view a list of products***, so that I can ***browse the store to know what to buy***
***

### ACCEPTANCE CRITERIA
- [ ] All products to be displayed for the user to see
- [ ] UX is visually appealing
***

### TASKS
- [ ] Create products page to show all items
- [ ] Customise styling
- [ ] Test functionality
