### ISSUE TITLE
USER STORY: Product details

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#7]
### EPIC: Navigating through the website

***

### USER STORY
As a ***shopper ***, I want to ***view details about an individual product***, so that I can ***see the product description, price, image, reviews, and be able to purchase the item***

***

### ACCEPTANCE CRITERIA
- [ ] Clicking on any item takes the user to the product detail page
- [ ] Product detail page shows the image, price, description, any reviews, and a button to purchase the item

***

### TASKS
- [ ] Create products detail page to show item information
- [ ] Customise styling
- [ ] Test functionality
