### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#8]
### EPIC: Sorting and searching for products

***

### USER STORY
As a ***shopper***, I want to ***sort the list of available products***, so that I can ***easily view the items alphabetically or by price***

***

### ACCEPTANCE CRITERIA
- [ ] User is able to sort all products by price or alphabetically
- [ ] Sorting capabilities should be clear and intuitive to use

***

### TASKS
- [ ] Add ability to sort products
- [ ] Customise styling
- [ ] Test functionality
