### ISSUE TITLE
USER STORY: Sort items by category

### ISSUE THREAD

**Issue by s-batish** [s-batish/hidden-gems#9]
### EPIC: Sorting and searching for products

***

### USER STORY
As a ***shopper***, I want to ***sort items by category***, so that I can ***view just the items I am interested in buying***

***

### ACCEPTANCE CRITERIA
- [ ] User is able to sort items by the vairous jewellery categories and within each category they can choose whether they want gold or silver
- [ ] Category sorting buttons to feature in the navbar

***

### TASKS
- [ ] Add categories to navbar
- [ ] Customise styling
- [ ] Test functionality
